config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: "dashboard#index"

  resources :messages
  resources :faqs
  resources :boosts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  
  get 'terms/', to: "terms#index"
  get 'privacy-policy/', to: "privacy#index"

  resources :states
  get 'home/index'
  get 'home/index_barter'
  get 'home/index_cash'
  get 'home/howitworks'
  resources :product_images
  resources :products 
  
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boost.rb
class Boost < ApplicationRecord
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
validates_presence_of :name, :email, :phone, :msg
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :state
	belongs_to :user
	has_many :product_images, dependent: :destroy
	has_many :boosts
	accepts_nested_attributes_for :product_images, update_only: true, :allow_destroy => true

	validates_presence_of :category_id, :message => ": Please select a category for this product"
	validates_presence_of :name, :message => ": Product Name can't be blank"
	validates_presence_of :description, :message => ": Please describe the product"
	validates_presence_of :state_id, :message => ": Please fill in the location of this product"
	validates_presence_of :condition, :message => ": Condition of the product must be set"


	# Friendly ID
	extend FriendlyId
  	friendly_id :name, use: :slugged

	default_scope { order(created_at: :desc) }

	before_save :set_id

	def set_id
		company = "SWP"
		time_id = Time.now.to_i.to_s.reverse[0..5]
		self.swap_id = company+time_id
	end

	
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
end

app/models/state.rb
class State < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord

  has_many :products
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:username]

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of    :email,    :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of    :password, :on=>:create
  validates_confirmation_of    :password, :on=>:create
  validates_length_of    :password, :within => Devise.password_length, :allow_blank => true
end

app/controllers/boosts_controller.rb
class BoostsController < InheritedResources::Base

  layout "swapper"

  def create
    create!(:notice => "You have boosted this item successfully") {product_path(Product.find(@boost.product_id))}
  end

  private

    def boost_params
      params.require(:boost).permit(:product_id, :boost_type, :paid, :status)
    end
end


app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  layout "swapper"

  def new
  	redirect_to admin_faqs_path  	
  end

  def show
  	redirect_to admin_faqs_path
  end

  def edit
  	redirect_to admin_faqs_path
  end

  private

    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end


app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boosts_helper.rb
module BoostsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/boosts/_form.html.erb
<% @product = Product.find_by_name(params[:product]) %>
<script src="https://js.paystack.co/v1/inline.js"></script>
<%= render "layouts/header" %>
    <div class="banner text-center">
        <div class="container">
            <h1>Boost Post </h1>
            <p>Select Boost Duration</p>
            <a href="<%= product_path(@product) %>">Back to Ad</a>
        </div>
    </div>
    <!--single-page-->
    <div class="single-page main-grid-border">
        <div class="container">
            <div class="post-ad-form">
              <%= form_for(boost) do |f| %>

                <% if boost.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(boost.errors.count, "error") %> prohibited this boost from being saved:</h2>

                    <ul>
                    <% boost.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>

                <%= f.hidden_field :product_id, value: @product.id %>

                <label>Boost Duration <span>*</span></label>
                <%= f.select(:boost_type, options_for_select([["Daily Boost: NGN200", "Day"], ["Weekly Boost: NGN1000", "Weekly"], ["Monthly Boost: NGN3500", "Monthly"]])) %>
                <div class="clearfix"></div>

                <%= f.hidden_field :paid, value: true %>
                
                <div class="personal-details">
                                        <input type="submit" onclick="payWithPaystack()" value="Boost this Ad" class="booster">
                                        <div class="clearfix"></div>
                </div>
            <div id="product_images_fields_blueprint" style="display: none" data-blueprint="
                              <input type=&quot;file&quot; name=&quot;product[product_images_attributes][new_product_images][image]&quot; id=&quot;product_product_images_attributes_new_product_images_image&quot; /><input name=&quot;product[product_images_attributes][new_product_images][_destroy]&quot; type=&quot;hidden&quot; value=&quot;0&quot; /><input type=&quot;checkbox&quot; value=&quot;1&quot; name=&quot;product[product_images_attributes][new_product_images][_destroy]&quot; id=&quot;product_pro duct_images_attributes_new_product_images__destroy&quot; /><span>Remove</span>
            <br>">
              
            </div>
          <% end %>
            </div>
            <div class="product-desc">
                <div class="col-md-7 product-view white">
                    <h2><%= @product.name %></h2>
                    <p> <i class="glyphicon glyphicon-map-marker"></i><%= link_to @product.state.title, @product.state %>| Added <%= time_ago_in_words(@product.created_at) %> ago, Ad ID: <%= @product.swap_id %></p>
                    <% if @product.product_images %>
                    <div class="flexslider">
                        <ul class="slides">
                            <% @product.product_images.each do |image| %>
                            <li data-thumb="<%= image.image_url(:slide) %>">
                                <%= image_tag image.image_url(:slide) %>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                    <% end %>
                    <!-- FlexSlider -->
                    <script defer src="/assets/jquery.flexslider.js"></script>
                    <link rel="stylesheet" href="/assets/flexslider.css" type="text/css" media="screen" />
                    <script>
                    // Can also be used with $(document).ready()
                    $(window).load(function() {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            controlNav: "thumbnails"
                        });
                    });
                    </script>

                    <style type="text/css">
                        .boost{
                            background: #f44804;
                            padding: 10px;
                            color: #ffffff;
                            border-radius:10px;
                            text-decoration: none;
                        }
                        .boost:hover{
                            background: #F55000;
                            text-decoration:none;
                        }
                    </style>
                    <!-- //FlexSlider -->
                    <div class="product-details">
                        <h4>Seller : <a href="#0"><%= @product.user.username || @product.user.first_name+@product.user.last_name %></a></h4>
                        <h4>Views : <strong><%= pluralize(@product.view_count, "view") %></strong></h4>
                        <p><strong>Description</strong> : <%= @product.description %></p>
                    </div>
                </div>
                <div class="col-md-5 product-details-grid">
                    <div class="item-price white">
                        <div class="product-price">
                            <p class="p-price">Price</p>
                            <h3 class="rate">&#8358; <%= number_to_currency(@product.price, unit: "", precision: 0) %></h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="condition">
                            <p class="p-price">Condition</p>
                            <h4><%= @product.condition %></h4>
                            <div class="clearfix"></div>
                        </div>
                        <div class="itemtype">
                            <p class="p-price">Item Type</p>
                            <h4>Phones</h4>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--//single-page-->
    <%= render "layouts/footer" %>

<script>
  var boostAmount
  $(".booster").click(function(event){
      event.preventDefault();
  });

  function payWithPaystack(){
    var boostAmount;
    boostDuration = document.getElementById('boost_boost_type').value;

    if (boostDuration === "Day"){
      boostAmount = 20000
    } else if (boostDuration === "Weekly"){
      boostAmount = 100000
    } else if (boostDuration === "Monthly") {
      boostAmount = 350000
    };

    var handler = PaystackPop.setup({
      key: 'pk_live_1becbb30ac18b981c6165d1df09088a4e61a7524',
      email: "<%= current_user.email %>",
      amount: boostAmount,
      ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
      metadata: {
         custom_fields: [
            {
                display_name: "Mobile Number",
                variable_name: "mobile_number",
                value: "+2348012345678"
            }
         ]
      },
      callback: function(response){
          alert('success. transaction ref is ' + response.reference);
          $("#new_boost").submit()
      },
      onClose: function(){
          alert('window closed');
      }
    });
    handler.openIframe();
  }
</script>

app/views/boosts/edit.html.erb
<h1>Editing Boost</h1>

<%= render 'form', boost: @boost %>

<%= link_to 'Show', @boost %> |
<%= link_to 'Back', boosts_path %>

app/views/boosts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Boosts</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Boost type</th>
      <th>Paid</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boosts.each do |boost| %>
      <tr>
        <td><%= boost.product_id %></td>
        <td><%= boost.boost_type %></td>
        <td><%= boost.paid %></td>
        <td><%= boost.status %></td>
        <td><%= link_to 'Show', boost %></td>
        <td><%= link_to 'Edit', edit_boost_path(boost) %></td>
        <td><%= link_to 'Destroy', boost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boost', new_boost_path %>

app/views/boosts/new.html.erb
<h1>New Boost</h1>

<%= render 'form', boost: @boost %>

<%= link_to 'Back', boosts_path %>

app/views/boosts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @boost.product_id %>
</p>

<p>
  <strong>Boost type:</strong>
  <%= @boost.boost_type %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @boost.paid %>
</p>

<p>
  <strong>Status:</strong>
  <%= @boost.status %>
</p>

<%= link_to 'Edit', edit_boost_path(@boost) %> |
<%= link_to 'Back', boosts_path %>