config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: "dashboard#index"

  resources :messages
  resources :faqs
  resources :boosts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  
  get 'terms/', to: "terms#index"
  get 'privacy-policy/', to: "privacy#index"

  resources :states
  get 'home/index'
  get 'home/index_barter'
  get 'home/index_cash'
  get 'home/howitworks'
  resources :product_images
  resources :products 
  
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boost.rb
class Boost < ApplicationRecord
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
validates_presence_of :name, :email, :phone, :msg
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :state
	belongs_to :user
	has_many :product_images, dependent: :destroy
	has_many :boosts
	accepts_nested_attributes_for :product_images, update_only: true, :allow_destroy => true

	validates_presence_of :category_id, :message => ": Please select a category for this product"
	validates_presence_of :name, :message => ": Product Name can't be blank"
	validates_presence_of :description, :message => ": Please describe the product"
	validates_presence_of :state_id, :message => ": Please fill in the location of this product"
	validates_presence_of :condition, :message => ": Condition of the product must be set"


	# Friendly ID
	extend FriendlyId
  	friendly_id :name, use: :slugged

	default_scope { order(created_at: :desc) }

	before_save :set_id

	def set_id
		company = "SWP"
		time_id = Time.now.to_i.to_s.reverse[0..5]
		self.swap_id = company+time_id
	end

	
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
end

app/models/state.rb
class State < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord

  has_many :products
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:username]

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of    :email,    :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of    :password, :on=>:create
  validates_confirmation_of    :password, :on=>:create
  validates_length_of    :password, :within => Devise.password_length, :allow_blank => true
end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  layout "swapper"

  def new
  	redirect_to admin_faqs_path  	
  end

  def show
  	redirect_to admin_faqs_path
  end

  def edit
  	redirect_to admin_faqs_path
  end

  private

    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end


app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "swapper"
  def index
  end

  def index_barter
  	@products = Product.where(barter: true)
  end

  def index_cash
  	@products = Product.where(barter: false)
  end

  def howitworks
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boosts_helper.rb
module BoostsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/faqs/_form.html.erb
<%= form_for(faq) do |f| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
      <% faq.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_area :answer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<h1>Editing Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Show', @faq %> |
<%= link_to 'Back', faqs_path %>

app/views/faqs/index.html.erb
<%= render "layouts/header" %>
    <div class="main-banner banner text-center">
        <div class="container">
            <h1>Sell or Trade   <span class="segment-heading">    by BARTER </span> with Swapper</h1>
            <p>The first trade by barter online system in Nigeria</p>
            <a href="<%= new_product_path %>">Post Free Ad</a>
        </div>
    </div>

<!-- Faq -->
  <div class="faq main-grid-border">
    <div class="container">
      <h2 class="head">Faqs</h2>
      <dl class="faq-list">
         <% @faqs.each do |faq| %>
        <dt class="faq-list_h">
        <h4 class="marker">Q?</h4>
        <h5 class="marker_head"><%= faq.question %></h5>
        </dt>
        <dd>
        <h4 class="marker1">A.</h4>
        <p class="m_13"><%= faq.answer %></p>
        </dd>
        <% end %>    
      </dl>
    </div>  
  </div>
<!-- // Faq -->
<%= render "layouts/footer" %>

app/views/faqs/new.html.erb
<h1>New Faq</h1>

<%= render 'form', faq: @faq %>

<%= link_to 'Back', faqs_path %>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>