config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: "dashboard#index"

  resources :messages
  resources :faqs
  resources :boosts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  
  get 'terms/', to: "terms#index"
  get 'privacy-policy/', to: "privacy#index"

  resources :states
  get 'home/index'
  get 'home/index_barter'
  get 'home/index_cash'
  get 'home/howitworks'
  resources :product_images
  resources :products 
  
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boost.rb
class Boost < ApplicationRecord
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
validates_presence_of :name, :email, :phone, :msg
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :state
	belongs_to :user
	has_many :product_images, dependent: :destroy
	has_many :boosts
	accepts_nested_attributes_for :product_images, update_only: true, :allow_destroy => true

	validates_presence_of :category_id, :message => ": Please select a category for this product"
	validates_presence_of :name, :message => ": Product Name can't be blank"
	validates_presence_of :description, :message => ": Please describe the product"
	validates_presence_of :state_id, :message => ": Please fill in the location of this product"
	validates_presence_of :condition, :message => ": Condition of the product must be set"


	# Friendly ID
	extend FriendlyId
  	friendly_id :name, use: :slugged

	default_scope { order(created_at: :desc) }

	before_save :set_id

	def set_id
		company = "SWP"
		time_id = Time.now.to_i.to_s.reverse[0..5]
		self.swap_id = company+time_id
	end

	
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
end

app/models/state.rb
class State < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord

  has_many :products
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:username]

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of    :email,    :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of    :password, :on=>:create
  validates_confirmation_of    :password, :on=>:create
  validates_length_of    :password, :within => Devise.password_length, :allow_blank => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout "swapper"
  def index
  end

  def index_barter
  	@products = Product.where(barter: true)
  end

  def index_cash
  	@products = Product.where(barter: false)
  end

  def howitworks
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boosts_helper.rb
module BoostsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/home/howitworks.html.erb
<%= render "layouts/header" %>
    <div class="main-banner banner text-center">
        <div class="container">
            <h1>Sell or Trade   <span class="segment-heading">    by BARTER </span> with Swapper</h1>
            <p>The first trade by barter online system in Nigeria</p>
            <a href="<%= new_product_path %>">Post Free Ad</a>
        </div>
    </div>
    <!-- content-starts-here -->
    <!-- How it works -->
		<div class="work-section">
			<div class="container">
				<h2 class="head">How It Works</h2>
					<div class="work-section-head text-center">
						<p>Fast, easy and free to post an ad and you will find, what you are looking for.</p>
					</div>
					<div class="work-section-grids text-center">
						<div class="col-md-3 work-section-grid">
							<i class="fa fa-pencil-square-o"></i>
							<h4>Post an Ad</h4>
							<p>Do you have a property for sale? or a shop, post free ads on swapper.com.ng</p>
							<span class="arrow1"><img src="/assets/arrow1.png" alt="" /></span>
						</div>
						<div class="col-md-3 work-section-grid">
							<i class="fa fa-eye"></i>
							<h4>Find an item</h4>
							<p>Looking for where to buy from? Hook up with people from your area</p>
							<span class="arrow2"><img src="/assets/arrow2.png" alt="" /></span>
						</div>
						<div class="col-md-3 work-section-grid">
							<i class="fa fa-phone"></i>
							<h4>contact the seller</h4>
							<p>Get quick access to sellers and transact faster</p>
							<span class="arrow1"><img src="/assets/arrow1.png" alt="" /></span>
						</div>
						<div class="col-md-3 work-section-grid">
							<i class="fa fa-money"></i>
							<h4>make transactions</h4>
							<p>Make payments and walk away with your purchased items</p>
						</div>
						<div class="clearfix"></div>
						<a class="work" href="<%= new_product_path %>">Get started Now!</a>
					</div>
				</div>
		</div>	
	<!-- // How it works -->
    <%= render "layouts/footer" %>

app/views/home/index.html.erb
<%= render "layouts/header" %>
    <div class="main-banner banner text-center" style="background-image: url(<%= asset_path 'barter.jpg' %>);">
        <div class="container">
            <h1 style="color:white;font-weight:400px;">Sell or Trade   <span class="segment-heading">    by BARTER </span> with Swapper</h1>
            <p style="color:white;font-weight:100px;">The first trade by barter online system in Nigeria</p>
            <a href="<%= new_product_path %>">Post Free Ad</a>
        </div>
    </div>
    <!-- content-starts-here -->
    <div class="content">
	 <div class="trending-ads">
            <div class="container white">
                <!-- slider -->
        
		   <div class="trend-ads">
                    <h2>Trending Ads</h2>
                    <ul id="flexiselDemo3">
                        <li>
                            <% Product.limit(4).each do |product| %>
                            <div class="col-md-3 biseller-column">
                                <a href="<%= product_path(product) %>">
                                            <%= image_tag product.product_images.first.image_url(:slide) %>
                                            <span class="price">&#8358; <%= number_to_currency(product.price, unit: "", precision: 0) %></span>
                                        </a>
                                <div class="ad-info">
                                    <h5><%= product.name %></h5>
                                    <span><%= time_ago_in_words(product.created_at) %> ago</span>
                                </div>
                            </div>
                            <% end %>
                        </li>
                        <li>
                            <% Product.offset(4).limit(4).each do |product| %>
                            <div class="col-md-3 biseller-column">
                                <a href="<%= product_path(product) %>">
                                            <%= image_tag product.product_images.first.image_url(:slide) %>
                                            <span class="price">&#8358; <%= number_to_currency(product.price, unit: "", precision: 0) %></span>
                                        </a>
                                <div class="ad-info">
                                    <h5><%= product.name %></h5>
                                    <span><%= time_ago_in_words(product.created_at) %> ago</span>
                                </div>
                            </div>
                            <% end %>
                        </li>
                        <li>
                            <% Product.offset(8).limit(4).each do |product| %>
                            <div class="col-md-3 biseller-column">
                                <a href="<%= product_path(product) %>">
                                            <%= image_tag product.product_images.first.image_url(:slide) %>
                                            <span class="price">&#8358; <%= number_to_currency(product.price, unit: "", precision: 0) %></span>
                                        </a>
                                <div class="ad-info">
                                    <h5><%= product.name %></h5>
                                    <span><%= time_ago_in_words(product.created_at) %> ago</span>
                                </div>
                            </div>
                            <% end %>
                        </li>
                    </ul>
                    <script type="text/javascript">
                    $(window).load(function() {
                        $("#flexiselDemo3").flexisel({
                            visibleItems: 1,
                            animationSpeed: 1000,
                            autoPlay: true,
                            autoPlaySpeed: 5000,
                            pauseOnHover: true,
                            enableResponsiveBreakpoints: true,
                            responsiveBreakpoints: {
                                portrait: {
                                    changePoint: 480,
                                    visibleItems: 1
                                },
                                landscape: {
                                    changePoint: 640,
                                    visibleItems: 1
                                },
                                tablet: {
                                    changePoint: 768,
                                    visibleItems: 1
                                }
                            }
                        });

                    });
                    </script>
                    <script type="text/javascript" src="/assets/jquery.flexisel.js"></script>
                </div>
            </div>
            <!-- //slider -->
        </div>
        <div class="categories">
            <div class="container white">
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Mobile")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-mobile"></i></div>
                                <h4 class="clrchg">Mobiles</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Electronics")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-laptop"></i></div>
                                <h4 class="clrchg"> Electronics & Appliances</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Cars")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-car"></i></div>
                                <h4 class="clrchg">Cars</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Bikes")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-motorcycle"></i></div>
                                <h4 class="clrchg">Bikes</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Furniture")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-wheelchair"></i></div>
                                <h4 class="clrchg">Furnitures</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Pets")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-paw"></i></div>
                                <h4 class="clrchg">Pets</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Books, Sports & Hobbies")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-book"></i></div>
                                <h4 class="clrchg">Books, Sports & Hobbies</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Fashion")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-asterisk"></i></div>
                                <h4 class="clrchg">Fashion</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Kids")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-gamepad"></i></div>
                                <h4 class="clrchg">Kids</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Services")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-smile"></i></div>
                                <h4 class="clrchg">Services</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Jobs")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-handshake"></i></div>
                                <h4 class="clrchg">Jobs</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-2 focus-grid">
                    <a href="<%= category_path(Category.find_by_title("Real Estate")) %>">
                        <div class="focus-border">
                            <div class="focus-layout">
                                <div class="focus-image"><i class="fa fa-home"></i></div>
                                <h4 class="clrchg">Real Estate</h4>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="mobile-app">
		 <div class="ads-grid">
            <%= render "products/featured" %>
	    </div>
            <div class="container">
                <div class="col-md-5 app-left">
                    <a href="#"><%= image_tag "app.png", style: "" %></a>
                </div>
                <div class="col-md-7 app-right">
                    <h3>Swapper is the <span>Easiest</span> platform for trading in barter</h3>
                    <p>It is the best and only e-commerce website based in nigeria to offer trade in the form of barter. It is user friendly, sensitive and easy to use. It provides adequate and neccessary tools needed for trade of any category or form. It's a one of a kind trade platform which is long over due necessary for business in nigeria.</p>

                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <%= render "layouts/footer" %>