config/routes.rb
Rails.application.routes.draw do
  
  get 'dashboard', to: "dashboard#index"

  resources :messages
  resources :faqs
  resources :boosts
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions"}
  
  get 'terms/', to: "terms#index"
  get 'privacy-policy/', to: "privacy#index"

  resources :states
  get 'home/index'
  get 'home/index_barter'
  get 'home/index_cash'
  get 'home/howitworks'
  resources :product_images
  resources :products 
  
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boost.rb
class Boost < ApplicationRecord
	belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
validates_presence_of :name, :email, :phone, :msg
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :state
	belongs_to :user
	has_many :product_images, dependent: :destroy
	has_many :boosts
	accepts_nested_attributes_for :product_images, update_only: true, :allow_destroy => true

	validates_presence_of :category_id, :message => ": Please select a category for this product"
	validates_presence_of :name, :message => ": Product Name can't be blank"
	validates_presence_of :description, :message => ": Please describe the product"
	validates_presence_of :state_id, :message => ": Please fill in the location of this product"
	validates_presence_of :condition, :message => ": Condition of the product must be set"


	# Friendly ID
	extend FriendlyId
  	friendly_id :name, use: :slugged

	default_scope { order(created_at: :desc) }

	before_save :set_id

	def set_id
		company = "SWP"
		time_id = Time.now.to_i.to_s.reverse[0..5]
		self.swap_id = company+time_id
	end

	
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
end

app/models/state.rb
class State < ApplicationRecord
	has_many :products

	# Friendly ID
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord

  has_many :products
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :authentication_keys => [:username]

  validates :username, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates_uniqueness_of    :email,     :case_sensitive => false, :allow_blank => true, :if => :email_changed?
  validates_format_of    :email,    :with  => Devise.email_regexp, :allow_blank => true, :if => :email_changed?
  validates_presence_of    :password, :on=>:create
  validates_confirmation_of    :password, :on=>:create
  validates_length_of    :password, :within => Devise.password_length, :allow_blank => true
end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base

  layout "swapper"

  def new
  	redirect_to admin_faqs_path  	
  end

  def show
  	redirect_to admin_faqs_path
  end

  def edit
  	redirect_to admin_faqs_path
  end

  private

    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end


app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :increment_view_count, only: [:show]

  layout "swapper"
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show

  end

  # GET /products/new
  def new
    @product = Product.new
    @product.product_images.build
  end

  # GET /products/1/edit
  def edit
    @product.product_images.build
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.friendly.find(params[:id])
    end

    # Count Views
    def increment_view_count
      p  = Product.friendly.find(@product.id)
      p.view_count = p.view_count+1
      p.save
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :category_id, :state_id, :condition, :barter, :price, :user_id, product_images_attributes: [:id, :image, :product_id, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boosts_helper.rb
module BoostsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/privacy_helper.rb
module PrivacyHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/products/_featured.html.erb
<div class="side-bar col-md-3">
    <div class="featured-ads">
        <h2 class="sear-head fer">Featured Ads</h2>
        <div class="featured-ad">
            <a href="#">
                <div class="featured-ad-left">
                    <img src="/assets/f1.jpg" title="ad image" alt="" />
                </div>
                <div class="clearfix"></div>
            </a>
        </div>
        <div class="featured-ad">
            <a href="#">
                <div class="featured-ad-left">
                    <img src="/assets/f2.jpg" title="ad image" alt="" />
                </div>
                <div class="clearfix"></div>
            </a>
        </div>
        <div class="featured-ad">
            <a href="#">
                <div class="featured-ad-left">
                    <img src="/assets/f3.jpg" title="ad image" alt="" />
                </div>
                <div class="clearfix"></div>
            </a>
        </div>
    </div>
</div>

app/views/products/_form.html.erb
<%= nested_form_for @product do |f| %>

    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <label>Select Category <span>*</span></label>
    <%= f.collection_select :category_id, Category.all, :id, :title, prompt: "Select Category" %>
    <div class="clearfix"></div>

    <%= f.label :name, "Ad Title" %>
    <%= f.text_field :name, placeholder: "Enter product name here" %>
    <div class="clearfix"></div>
    
    <label>Ad Description <span>*</span></label>
    <%= f.text_area :description, placeholder: "Write few lines about your product" %>
    <div class="clearfix"></div>

    <%= f.label :name, "Ad Condition <span>*</span>".html_safe %>
    <%= f.select :condition, options_for_select([["New", "New"], ["Fairly Used", "Fairly Used"], ["Old", "Old"]]) %>
    <div class="clearfix"></div>

    <%= f.label :price, "Ad Price<span>*</span>".html_safe %>
    <%= f.number_field :price %>
    <div class="clearfix"></div>

    <%= f.label :state_id, "Ad Location<span>*</span>".html_safe %>
    <%= f.collection_select :state_id, State.all, :id, :title, prompt: "Select State" %>
    <div class="clearfix"></div>
    
    <div class="upload-ad-photos">
        <label>Photos for your ad :</label>
        <div class="photos-upload-view">
            <input type="hidden" id="MAX_FILE_SIZE" name="MAX_FILE_SIZE" value="300000" />
            <div>
                <%= f.fields_for :product_images, wrapper:false do |image| %>
                  <%= render 'images', f: image %>
                <% end %>
            </div>

            <%= f.link_to_add :product_images, class: "add-link" do %>
            <i class="fa fa-plus-circle" aria-hidden="true"></i> Add Image
            <% end %>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="upload-ad-photos">
        <label>Trade Type<span>*</span> :</label>
        <%= f.check_box :barter %><span>Do you want to trade this product by Barter?</span>
        <div class="clearfix"></div>
    </div>
    
    <div class="personal-details">
        <p class="post-terms">By clicking <strong>post Button</strong> you accept our <a href="<%= terms_path %>" target="_blank">Terms of Use </a> and <a href="<%= privacy_policy_path %>" target="_blank">Privacy Policy</a></p>
                            <input type="submit" value="Post">
                            <div class="clearfix"></div>
    </div>
<% end %>

app/views/products/_images.html.erb
<%= f.file_field :image %><%= f.check_box :_destroy %><span>Remove</span>
<br>

app/views/products/edit.html.erb
<%= render "layouts/header" %>
    <div class="banner text-center">
        <div class="container">
            <h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Swapper</h1>
            <p>Nigeria's number one trade by barter platform</p>
        </div>
    </div>
    <!-- Submit Ad -->
    <div class="submit-ad main-grid-border">
        <div class="container">
            <h2 class="head">Editing Product</h2>
            <div class="post-ad-form">
            	<%= render 'form', product: @product %>
            </div>
        </div>
    </div>
    <!-- // Submit Ad -->
<%= render "layouts/footer" %>

app/views/products/new.html.erb
<%= render "layouts/header" %>
    <div class="banner text-center">
        <div class="container">
            <h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Swapper</h1>
            <p>Nigeria's number one trade by barter platform</p>
        </div>
    </div>
    <!-- Submit Ad -->
    <div class="submit-ad main-grid-border">
        <div class="container">
            <h2 class="head">Create a new Product</h2>
            <div class="post-ad-form">
            	<%= render 'form', product: @product %>
            </div>
        </div>
    </div>
    <!-- // Submit Ad -->
<%= render "layouts/footer" %>

app/views/products/show.html.erb
<style type="text/css">
    .redBox {
        background: green;
        width: 100%;
        height: 50px;
        z-index: 1000;
        text-align: center;
        padding: 13px 0px;
        color: #fff;
        text-transform: uppercase;
    }
</style>


<%= render "layouts/header" %>
    <div class="banner text-center">
        <div class="container">
            <h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Swapper</h1>
            <p>Nigeria's number one trade by barter platform</p>
            <a href="<%= new_product_path %>">Post Free Ad</a>
        </div>
    </div>
    <!--single-page-->
    <% if flash[:notice] %>
    <div class="redBox">
        <%= flash[:notice] %>
    </div>
    <% end %>
    <div class="single-page main-grid-border">
        <div class="container">
            <ol class="breadcrumb" style="margin-bottom: 5px;">
                <li><a href="<%= root_url %>">Home</a></li>
                <li><a href="<%= products_path %>">All Ads</a> </li>
                <li class="active"><%= link_to @product.category.title, @product.category %></li>
                <li class="active"><%= @product.name %></li>
            </ol>
            <div class="product-desc">
                <div class="col-md-7 product-view white">
                    <h2><%= @product.name %></h2>
                    <p> <i class="glyphicon glyphicon-map-marker"></i><%= link_to @product.state.title, @product.state %>| Added <%= time_ago_in_words(@product.created_at) %> ago, Ad ID: <%= @product.swap_id %></p>
                    <% if @product.product_images %>
                    <div class="flexslider">
                        <ul class="slides">
                            <% @product.product_images.each do |image| %>
                            <li data-thumb="<%= image.image_url(:slide) %>">
                                <%= image_tag image.image_url(:slide) %>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                    <% end %>
                    <!-- FlexSlider -->
                    <script defer src="/assets/jquery.flexslider.js"></script>
                    <link rel="stylesheet" href="/assets/flexslider.css" type="text/css" media="screen" />
                    <script>
                    // Can also be used with $(document).ready()
                    $(window).load(function() {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            controlNav: "thumbnails"
                        });
                    });
                    </script>

                    <style type="text/css">
                        .boost{
                            background: #f44804;
                            padding: 10px;
                            color: #ffffff;
                            border-radius:10px;
                            text-decoration: none;
                        }
                        .boost:hover{
                            background: #F55000;
                            text-decoration:none;
                        }
                    </style>
                    <!-- //FlexSlider -->
                    <div class="product-details">
                        <h4>Seller : <a href="#0"><%= @product.user.username || @product.user.first_name+@product.user.last_name %></a></h4>
                        <h4>Views : <strong><%= pluralize(@product.view_count, "view") %></strong></h4>
                        <p><strong>Description</strong> : <%= @product.description %></p>
                        <% if @product.user == current_user %>
                        <p><a href="<%= new_boost_path(product: @product.name) %>" class="boost" style="color:#fff">Boost Post</a></p>
                        <% end %>
                    </div>
                </div>
                <div class="col-md-5 product-details-grid">
                    <div class="item-price white">
                        <div class="product-price">
                            <p class="p-price">Price</p>
                            <h3 class="rate">&#8358; <%= number_to_currency(@product.price, unit: "", precision: 0) %></h3>
                            <div class="clearfix"></div>
                        </div>
                        <div class="condition">
                            <p class="p-price">Condition</p>
                            <h4><%= @product.condition %></h4>
                            <div class="clearfix"></div>
                        </div>
                        <div class="itemtype">
                            <p class="p-price">Item Type</p>
                            <h4>Phones</h4>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="interested text-center">
                        <h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
                        <p><i class="fa fa-phone"></i><%= @product.user.phone %></p>
                    </div>
							
					
                    <div class="tips">
                        <h4>Safety Tips for Buyers</h4>
                        <ol>
                            <li><a href="#0">Never pay before purchase.</a></li>
                            <li><a href="#0">Try to meet at a safe,public location for both cash and especially barter trades.</a></li>
                            <li><a href="#0">Check the item before you buy and exchange for it.</a></li>
                            <li><a href="#0">Always ensure that a transport means is always available for the size,quantity and quality of a goods bought or bartered.</a></li>
                            <li><a href="#0">Pay only after collecting and securing item.</a></li>
                        </ol>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <!--//single-page-->
    <%= render "layouts/footer" %>